name: CICD

on:
  push:
    branches: [deploy]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/spring-boot-github-actions .
      - name: Publish Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/spring-boot-github-actions:latest

  deploy:
    needs: build
    runs-on: [ready]
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/spring-boot-github-actions:latest
      - name: Delete Old Container
        run: docker rm -f spring-boot-github-actions-container
      - name: Run Docker Container
        run: docker run -d -p 970:970 --name spring-boot-github-actions-container ${{ secrets.DOCKER_USERNAME }}/spring-boot-github-actions:latest